# Generated by Django 3.1.2 on 2020-11-04 14:48

from django.db import migrations, models
import main.custom_validators.custom_username_validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[main.custom_validators.custom_username_validators.CustomUnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
