# Generated by Django 3.1.2 on 2020-11-06 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201106_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='icon',
            new_name='icon_base_64',
        ),
    ]
