# Generated by Django 3.1.2 on 2020-11-11 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_video', to='main.video'),
        ),
    ]
