# Generated by Django 3.1.2 on 2020-11-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201111_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('data', models.DateField()),
                ('url', models.TextField()),
                ('image', models.ImageField(blank=True, default='', upload_to='media/images/')),
            ],
            options={
                'db_table': 'Events',
                'unique_together': {('name', 'data')},
            },
        ),
    ]
