# Generated by Django 3.1.2 on 2020-10-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_base_64',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
