# Generated by Django 3.1.2 on 2020-10-17 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_category_icon_base_64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
