# Generated by Django 3.1.2 on 2020-10-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon_base_64',
            field=models.TextField(),
        ),
    ]
