# Generated by Django 3.1.2 on 2020-10-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201019_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.AddField(
            model_name='category',
            name='icon_base_64_1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_base_64',
            field=models.TextField(default=''),
        ),
    ]
