# Generated by Django 3.1.2 on 2020-11-25 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_conference'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='conference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.conference'),
        ),
    ]
