# Generated by Django 3.1.2 on 2020-11-25 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_video_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.resource'),
        ),
    ]
