# Generated by Django 3.1.2 on 2020-12-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201126_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('src', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Author',
            },
        ),
        migrations.RemoveField(
            model_name='video',
            name='conference',
        ),
        migrations.DeleteModel(
            name='Conference',
        ),
    ]
