# Generated by Django 3.1.2 on 2020-12-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20201202_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='src',
            field=models.TextField(),
        ),
    ]
