# Generated by Django 3.1.2 on 2020-10-31 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20201031_1901'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NameCategoryForSearch',
            new_name='CategoryNames',
        ),
        migrations.CreateModel(
            name='SubcategoryNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subcategory')),
            ],
            options={
                'db_table': 'Subcategory names',
            },
        ),
    ]
