# Generated by Django 3.1.2 on 2020-11-03 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20201031_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='icon_base_64',
            new_name='icon',
        ),
    ]
