# Generated by Django 3.1.2 on 2020-12-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20201202_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='src',
            field=models.TextField(default='https://www.youtube.com/'),
        ),
    ]
