# Generated by Django 3.1.2 on 2020-12-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_resource_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='src',
            field=models.TextField(),
        ),
    ]
