# Generated by Django 3.1.2 on 2020-12-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_video_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='src',
            field=models.CharField(max_length=30),
        ),
    ]
