# Generated by Django 3.1.2 on 2020-12-06 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20201205_1541'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourites',
            new_name='FavouritesVideos',
        ),
        migrations.AlterModelTable(
            name='favouritesvideos',
            table='FavoritesVideos',
        ),
        migrations.CreateModel(
            name='FavoritesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'FavoritesCategory',
                'unique_together': {('category', 'user')},
            },
        ),
    ]
