# Generated by Django 3.1.2 on 2020-12-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_progressvideowatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressvideowatch',
            name='is_last',
            field=models.BooleanField(default=False),
        ),
    ]
