# Generated by Django 3.1.2 on 2020-12-30 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_progressvideowatch_is_last'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressvideowatch',
            name='is_last',
        ),
        migrations.CreateModel(
            name='LastWatchVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.video')),
            ],
            options={
                'db_table': 'Last video',
            },
        ),
    ]
