# Generated by Django 3.1.2 on 2021-01-06 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_notifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ['date']},
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='data',
            new_name='date',
        ),
    ]
